<a href="https://colab.research.google.com/github/angelarome/Solucion-de-ecuaciones-no-lineales/blob/main/Soluci%C3%B3n_de_Ecuaciones_no_lineales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ejercicio 1:
Plantamiento 1




In [3]:
import numpy as np

# Matriz de coeficientes
A = np.array([[2, 3, 1],
             [4, 1, 2],
             [3, 4, 2]], dtype=float)

# Vector de términos independientes
b = np.array([0.5, 1.0, 1.5], dtype=float)

# Resolviendo el sistema de ecuaciones usando eliminación de Gauss
sol = np.linalg.solve(A, b)

# Mostrar la solución
print("Solución del sistema:")
print(f"x = {sol[0]:.4f}, y = {sol[1]:.4f}, z = {sol[2]:.4f}")


Solución del sistema:
x = -0.5000, y = -0.0000, z = 1.5000


Plantamiento 2

In [5]:
import numpy as np

# Matriz de coeficientes
A = np.array([[3, -0.1, -0.2],
             [0.1, 0.7, -0.3],
             [0.3, -0.2, 10]], dtype=float)

# Vector de términos independientes
b = np.array([7.85, -19.3, 71.4], dtype=float)

# Resolviendo el sistema de ecuaciones usando eliminación de Gauss
sol = np.linalg.solve(A, b)

# Mostrar la solución
print("Solución del sistema:")
print(f"x = {sol[0]:.4f}, y = {sol[1]:.4f}, z = {sol[2]:.4f}")


Solución del sistema:
x = 2.2191, y = -25.0719, z = 6.5720


Ejercicio 2: Matriz inversa para calcular los pesos ajustados

In [6]:
# Matriz de coeficientes
A = np.array([[3, -0.1, -0.2],
              [0.1, 0.7, -0.3],
              [0.3, -0.2, 10]], dtype=float)

# Vector e salida deseada
b = np.array([7.85, -19.3, 71.4], dtype=float)

# Calcular la matriz inversa de A
A_inv = np.linalg.inv(A)

# Multiplicar A_inv por el vector b
sol = np.dot(A_inv, b)

# Mostrar la solución
print("Pesos ajustados:")
print(f"w1 = {sol[0]:.4f}, w2 = {sol[1]:.4f}, w3 = {sol[2]:.4f}")

Pesos ajustados:
w1 = 2.2191, w2 = -25.0719, w3 = 6.5720


Ejercicio 3: Método de Jacobi

In [7]:
def jacobi(A, b, x0, tol=1e-10, max_iter=1000):
  n = len(b)
  x = x0
  for k in range(max_iter):
    x_new = np.zeros_like(x)
    for i in range(n):
      s = sum(A[i][j] * x[j] for j in range(n) if i !=j)
      x_new[i] = (b[i] - s) / A[i][i]
    if np.linalg.norm(x_new - x, ord=np.inf) < tol:
      return x_new
    x = x_new
  return x

# Matriz de coeficientes
A = np.array([[3, -0.1, -0.2],
              [0.1, 0.7, -0.3],
              [0.3, -0.2, 10]], dtype=float)

# Vector de errores
b = np.array([7.85, -19.3, 71.4], dtype=float)

#Aproximación inicial
x0 = np.zeros_like(b)

# Aplicar el método de Jacobi
sol = jacobi(A, b, x0)

print("Pesos ajustados usando Jacobi:")
print(sol)

Pesos ajustados usando Jacobi:
[  2.21907032 -25.07187128   6.57199046]


Ejercicio 4: MÉTODO ITERATIVO DE GAUSS-SEIDEL

In [ ]:
import numpy as np

def gauss_seidel(A, b, x0, tol=1e-10, max_iter=1000):
    n = len(b)
    x = x0
    for k in range(max_iter):
      x_new = np.copy(x)
      for i in range(n):
        s1 = sum(A[i][j] * x_new[j] for j in range(i))
        s2 = sum(A[i][j] * x[j] for j in range(i+1, n))
        x_new[i] = (b[i] - s1 - s2) / A[i][i]
      if np.linalg.norm(x_new - x, ord=np.inf) < tol:
        return x_new, k
      x = x_new
    return x, max_iter

# Matriz de coeficientes
A = np.array([[10, -1, 2],
              [-1, 11, -1],
              [2, -1, 10]], dtype=float)

# Vector de tperminos independientes
b = np.array([5, 6, 7], dtype=float)

# Valor inicial de las incógnitas
x0 = np.zeros_like(b)

# Resolver el sistema usando el método de Gauss-Seidel
sol, iteraciones = gauss_seidel(A, b, x0)

# Mostrar la solución y el número de iteraciones
print("Solución del sistema:")
print(sol)
print(f"Número de iteraciones: {iteraciones}")

Ejercicio 5: Descomposición Cholesky

In [10]:
from scipy.linalg import cholesky

# Matriz y vector
A = np.array([[25, 15, -5],
              [15, 18, 0],
              [-5, 0, 11]], dtype=float)

b = np.array([350, 400, 200], dtype=float)

# Descomposición de Cholesky
L = cholesky(A, lower=True)

# Resolver Ly = b
y = np.linalg.solve(L, b)

# Resolver L^T x= y
x = np.linalg.solve(L.T, y)

# Mostrar la solución
print("Solución del sistema:")
print(x)

# Resolver L^T x = y
x = np.linalg.solve(L.T, y)

# Mostrar la solución
print("Pesos ajustados usando Cholesky:")
print(x)

Solución del sistema:
[10.51851852 13.45679012 22.96296296]
Pesos ajustados usando Cholesky:
[10.51851852 13.45679012 22.96296296]
